name: Python CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run tests
      run: |
        python -m pytest test_quiz.py -v --cov=app --cov-report=term-missing
      env:
        FLASK_ENV: testing

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Render
      uses: render-actions/deploy@v1
      with:
        render-token: ${{ secrets.RENDER_TOKEN }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        timeout-minutes: 5
